#login Page Elements

loginusername="name:username"
loginpassword="name:password"
loginbutton="xpath://button[contains(text(),'Log in')]"


#Registration Page Elements

# txt_firstname="name:name"
# txt_lname="xpath://body/section[@id='wrapper']/div[1]/div[1]/div[1]/form[1]/fieldset[1]/p[2]/input[1]"
# sel_country="//body/section[@id='wrapper']/div[1]/div[1]/div[1]/form[1]/fieldset[4]/select[1]"
# sel_month="//body[1]/section[1]/div[1]/div[1]/div[1]/form[1]/fieldset[5]/div[1]/select[1]"
# sel_Day="//body[1]/section[1]/div[1]/div[1]/div[1]/form[1]/fieldset[5]/div[2]/select[1]"
# sel_year="//body[1]/section[1]/div[1]/div[1]/div[1]/form[1]/fieldset[5]/div[3]/select[1]"
# txt_phone1="name:phone"
# txt_user="name:username"
# txt_email1="name:email"
# txt_psd="name:password"
# txt_cpsd="name:c_password"
# submit_btn="xpath://body/section[@id='wrapper']/div[1]/div[1]/div[1]/form[1]/fieldset[13]/input[1]"


#Registration1 Page Elements

# firsname="xpath://body/section[@id='section']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/input[1]"
# lastname="xpath://body/section[@id='section']/div[1]/div[1]/div[2]/form[1]/div[1]/div[2]/input[1]"
# txt_address="xpath://body/section[@id='section']/div[1]/div[1]/div[2]/form[1]/div[2]/div[1]/textarea[1]"
# txt_email="xpath://body/section[@id='section']/div[1]/div[1]/div[2]/form[1]/div[3]/div[1]/input[1]"
# txt_phone="xpath://body/section[@id='section']/div[1]/div[1]/div[2]/form[1]/div[4]/div[1]/input[1]"
# sel_gender="radiooptions"
# chek_hobby="xpath://input[@id='checkbox2']"
# sel_skills="xpath://body[1]/section[1]/div[1]/div[1]/div[2]/form[1]/div[8]/div[1]/select[1]"
# sel_ctry="xpath://body[1]/section[1]/div[1]/div[1]/div[2]/form[1]/div[10]/div[1]/select[1]"
# chose_year="xpath://select[@id='yearbox']"
# chose_month="xpath://body/section[@id='section']/div[1]/div[1]/div[2]/form[1]/div[11]/div[2]/select[1]"
# chose_day="xpath://select[@id='daybox']"
# txt_password="xpath://input[@id='firstpassword']"
# txt_confpassword="xpath://input[@id='secondpassword']"
# sub_btn="xpath://button[@id='submitbtn']"


#CMS Testing
txt_Username="name:email"
txt_password="name:password"
submit_button="xpath://button[@type='submit']"
hover_logoout="xpath://div[@class='sc-ihgnxF knIImG']"
logout_button="//a[@class='d-inline-block logoutLink']"
forgot_password="//a[normalize-space()='I forgot my password']"
txt_recovryemail="//input[@placeholder='Enter email']"
sub_sendemail="//button[@type='submit']"
back_login="//a[normalize-space()='back to login']"
new_password="//input[@placeholder='New Password']"
confirm_password="//input[@placeholder='Confirm New Password']"
sub_confirmpassword="//button[@type='submit']"
sel_graph14="css:body > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > section:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2)"
sel_Stress_Health="css:body > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > section:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(2) > li:nth-child(4) > div:nth-child(1)"
sel_21daysdata="css:body > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > section:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3)"
sel_7daysdata="css:body > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > section:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)"
sel_Mood="css:body > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > section:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(2) > li:nth-child(2) > div:nth-child(1)"
sel_Physical_Activity="css:body > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > section:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(2) > li:nth-child(7) > div:nth-child(1)"
Sel_peoplesection="//a[@href='/people']"
Sel_peoplecheckbox="//input[@class='checkbox']"
move_mousePeople="//div[@class='sc-kAyceB eAbRNa']"
sel_search="//input[@placeholder='Search']"
sel_name="//tbody//tr//td[2]"
Click_searchicon="//img[@alt='FilterImage']"
Select_checkbox="//input[@class='checkbox']"
sel_import="//button[@type='submit']"
cancel_file="//button[@class='fileCancel']"
upload_file="//input[@type='file'] "
Staff_section="//a[@href='/staff']"
Sel_checkbox1="//tbody/tr[2]/td[1]/input[1]"
Click_AddStaff="//button[@type='submit']"
txt_addstaffName="//input[@placeholder='Name']"
text_staffemail="//input[@placeholder='Email']"
sel_cancel="//button[@class='sc-aXZVg bCmdnD btn-transparent me-2']"
sel_save="//button[@class='sc-aXZVg bCmdnD save-btn']"
click_Report="//span[normalize-space()='reports']"
Dropdown_report="//div[@class='col-sm-12 col-md-6 col-lg-6 dropDownDiv']//select[@id='days']"
mouseover_noofuser="//canvas[@class='doughnut']"
Sel_per_metrics="//div[@class='col-lg-2 mt-1 mb-1']//select[@id='days']"
Sel_goal="css:body > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > section:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3)"
Sel_badges="//div[@class='sc-kAyceB eAbRNa']//img[2]"